#+++++++++++++++++
#+  N E T H E R  +
#+  C O N F I G  +
#+++++++++++++++++

nm-enabled: true

#Enable different additions in nether
enable_ambient_sounds: true
enable_better_fire: true
nether_lightning: true
soulsand_slowness: true
netherrack_fires: true
enable_custom_mobs: true
enable_mean_ghasts: true
enable_lava_burns: true
enable_lava_placement: true
enable_lava_spouts: true
enable_falling_nether: true
enable_nether_structures: true
enable_alpha_pigman_sword_drop: true
wither_potion_drops: true
haste_potion_drops: true
extended_wither_boss: false
enderman_growl_replace_enderdragon_growl: false
encrypted_chat: true

#Spawn rate/percentage chances
lightning_chance: 0.003
netherack_melting_chance: 3
netherrack_fire_chance: 10
mob_spawn_chance: 100
falling_nether_chance: 1
alpha_pigman_sword_drop_chance: 1
wind_volume: 800 #-lower equals louder
wind_pitch: 0 #-must be between 0 and 2
low_y_value_wind: 70
high_y_value_wind: 200
netherrack_step_sound: ENTITY_SLIME_SQUISH
wither_potion_drop_chance: 2
haste_potion_drop_chance: 2

#Structure spawn rate/percentage chance
all_structures_chance: 65
web_vine_chance: 50
mushroom_chance: 35
nether_spike_chance: 60
nether_world_height: 120
coral_chance: 60
rose_chance: 60
mushrooms_chance: 35
replace_netherrack_chance: 50

#Enable custom mobs
spawn_molten: true
spawn_fireball: true
spawn_inferno: true
spawn_old_shadow: true
spawn_sherogath: true
spawn_sadness: true
spawn_necromancer: true
spawn_alpha_pigman: true

#Custom mob spawn chance
molten_chance: 40
fireball_chance: 40
inferno_chance: 40
old_shadow_chance: 40
sherogath_chance: 40
sadness_chance: 40
necromancer_chance: 40
alpha_pigman_chance: 40

#Choose custom mob names
molten: '&6Molten'
fireball: '&2Fireball'
inferno: '&3Inferno'
old_shadow: '&4Old Shadow'
sherogath: '&7Sherogath'
sadness: '&9Sadness'
necromancer: '&4Necromancer'
alpha_pigman: '&4Alpha Pigman'

#List of worlds the plugin is enabled in
'enabled_worlds':
  - world_nether
