name: VeryDangerousNether
version: 2.0.0
main: verydangerousnether.verydangerousnether.main
api-version: 1.14
load: STARTUP
depend:
  - LibsDisguises
  - ProtocolLib
  - WorldEdit

commands:
  vdn:
    description: Allows spawn and reload
    usage: /vdn
    permission: verydangerousnether.vdc
    permission-message: You don't have the verydangerousnether.vdc permission.
