name: VeryDangerousNether
version: 1.0-SNAPSHOT
main: verydangerousnether.verydangerousnether.main
api-version: 1.14
load: STARTUP

commands:
  getworldnamed:
    description: Gets the name of the world you are in for use in config.
    usage: /getworldnamed
    permission: verydangerousnether.getworldname
    permission-message: You don't have the verydangerousnether.getworldname permission.
